#!/bin/bash

AUTHORS_FILE="AUTHORS"

echo "# File @generated by generate_authors.sh. DO NOT EDIT." > "$AUTHORS_FILE"
echo "# This file lists all contributors to the repository." >> "$AUTHORS_FILE"
echo "# See generate_authors.sh to make modifications." >> "$AUTHORS_FILE"
echo "" >> "$AUTHORS_FILE"

git log --format='%aN <%aE>' | sort -uf >> "$AUTHORS_FILE"

echo "Authors file has been generated at $AUTHORS_FILE"